services:

  db:
    image: "mysql:9.0.1"
    container_name: "students_management"
    restart: always
#    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: T_STUDENTS
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
